name: navigation
description: Application navigation layer
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  core:
   path: ../core 
  onboarding:
   path: ../features/onboarding/

  auto_route: 5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: 5.0.3                    
  build_runner: ^2.3.3
  
flutter:

